### ISSUE TITLE
Bugi

### ISSUE THREAD

**Issue by pyotrr** [bchronowski98/todo-app-better#8]
- [x] możliwość edytowania jednego taska na raz
- [x] input do edycji taska powinien być uzupełniony obecną wartością `task.content`
- [x] keyboard navigation
- [x] blokowanie możliwości ukończenia taska jeśli jest w trybie edycji
- [x] outside click na widgecie pogody
- [x] ekran skacze przy otwieraniu widgetu pogody
- [x] edycja taska zmienia jego stan na aktywny
- [x] za dużo pustego miejsca po bokach ekranu (desktop i mobile) 
- [x] pionowy scrollbar nawet jeśli nie ma tasków

**Comment by bchronowski98** [comment]
keyboard navi ??
